language: node_js
node_js:
  - '6'
  - '4'
branches:
  only:
    - master
    - /^release\/.*$/
    - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
